### ISSUE TITLE
Finish importing Botwinders Antispam tools

### ISSUE THREAD

**Issue by D0cR3d** [r-DestinyTheGame/Sweeper-Bot#100]
Botwinder currently handles the remaining aspects of our anti-spam tools. These need to be migrated into Sweeper Bot.

Ideally if any of these get tripped, then a message should be sent to the user telling them to stop doing that. If they continue doing it then they should get muted. Once a mute is in place, then a message should be sent to the mod channel letting us know action was taken.

Some logic that I'd like to see:

If user starts approaching the mass message spam limit then send them a warning "You are about to be muted for sending messages too quickly". If they break that on 1st offence then give a short 20 minute mute, warn the user, warn the mod team, log their messages sent, and delete the messages. If they spam again for a 2nd time within 2 hours of their prior mute then mute them for 6 hours and ping @here in the mod channel, with same logging.

Upon initial release we will need to do a lot of data analytics to log how often this would get tripped and find a happy medium where it wouldn't trigger too often, but only those that are coming in just to spam. During this phase it would be reporting only, no notice to user or any removals or muting of anyone.

- [x] Mass message spam (multiple messages of same/similar text)
- [x] Mass user mention spam (mentiong more than x people in a single or multiple messages)
- [x] Remove all discord server invites
  - [x]  Bonus if it can leave invites going to our own server alone. At least whitelist Discord.gg/DestinyReddit

It seems anything linking to 'discord.gg' or 'discord.me' is an invite. So just need to `if message contains 'invite domain' then remove unless it's 'discord.gg/DestinyReddit'`

**Comment by dmbutalsodm** [comment]
Sounds like a user issue. Ticket closed.
