### ISSUE TITLE
node dependencies broken

### ISSUE THREAD

**Issue by petabytestorage** [r-DestinyTheGame/Sweeper-Bot#103]
I can't follow the developer guide to install node dependencies. I tried within docker and outside docker. Looks yamdbf related. Logfile attached from `docker built -t bot .`. Any info much appreciated.
[logfile.txt](https://github.com/r-DestinyTheGame/Sweeper-Bot/files/1232238/logfile.txt)  i am on ubuntu 16.04

**Comment by eddiewang** [comment]
#104

**Comment by aleksclark** [comment]
This seems to be a product of: https://github.com/npm/npm/issues/17781

**Comment by katagatame** [comment]
@aleksclark has it.  Downgrading node works around this for the time being.
