### ISSUE TITLE
Sweeper DM's - Add notice about DM Server

### ISSUE THREAD

**Issue by D0cR3d** [r-DestinyTheGame/Sweeper-Bot#111]
Add a notice to most messages that Sweeper Bot sends to let users know that messages sent to Sweeper Bot are ready by the moderation team and that we as mods can read and reply to them there. That they can use Sweeper DMs as a mod mail to us vs in public, and that we delete the messages when no longer needed and will be deleted by request.

Will need to make that a shorter statement.

Essentially should be added to the main help command, ban/warn/mute notices, etc.

**Comment by katagatame** [comment]
Would we need to do this if we complete #130?
