### ISSUE TITLE
Voice Channel Manager: Improvements

### ISSUE THREAD

**Issue by D0cR3d** [r-DestinyTheGame/Sweeper-Bot#123]
1. Always keep at least 2 channels open, possibly 3.

2. Move empty channels to the top of the list, makes easier for people to find open rooms.

3. Two Ikora voice channels. https://i.imgur.com/JobTg66.png

   _... more to come._

**Comment by katagatame** [comment]
1. Possibly a command to control that, `.vcm default 2` or something.

2. We should take time now and really think about the order and organization of the list.  Will help me make improvements. 

   _... more to come._

**Comment by D0cR3d** [comment]
I've also noticed some audio channels are sticking around a lot longer than the 1 minute they should be. These (https://i.imgur.com/IbnWeJX.png) have been hanging out for 5+ minutes now (I manually moved them up for the screenshot).

Granted if they hang around a little longer than 1 min then not going to care, but it _is_ an actual bug.

**Comment by katagatame** [comment]
Most of these were addressed in #131, leaving this open as channel categories have been released on to Canary.  They will be introduced to PTB and then live fairly shortly.

We will need to make some changes to adjust for channel categories.

**Comment by D0cR3d** [comment]
This has been completed.
