### ISSUE TITLE
VCM: Errors and not setting size correctly

### ISSUE THREAD

**Issue by D0cR3d** [r-DestinyTheGame/Sweeper-Bot#136]
When a voice channel is created, getting error:

```
0|Sweeper- | bitrate: int value should be greater than or equal to 8000.
0|Sweeper- | (node:31985) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 18066): DiscordAPIError: Invalid Form Body
```

Also not setting fireteam voice channel size limit correctly

<img width="234" alt="screen shot 2017-09-23 at 3 31 30 pm" src="https://user-images.githubusercontent.com/13460915/30776890-6d35cf80-a074-11e7-903a-89d0434cb894.png">

**Comment by katagatame** [comment]
This must have been recently implemented, as I am cloning an existing channel.  These errors were not appearing before.

I'll make adjustments.

**Comment by D0cR3d** [comment]
Issue has been resolved by a previous commit.
