### ISSUE TITLE
Complete updated list of VC names (including existing, minus duplicates)

### ISSUE THREAD

**Issue by quiscalusmajor** [r-DestinyTheGame/Sweeper-Bot#155]
'Abyss', 'Acolyte', 'Adjuticator', 'Adonna', 'Agah', 'Agema', 'Agenda-5', 'Ahamkara', 'Aksis', 'Aksor', 'Alak-Hul', 'Alessa', 'Alpha Lupi', 'Alzok', 'Amanda', 'Amytis', 'Ana', 'Andal', 'Anomaly', 'Arach', 'Aral', 'Arath', 'Archon', 'Arcblade', 'Arcology', 'Arcstrider', 'Armillary', 'Aru\'Un', 'Ascendant Raisins', 'Asher', 'Atheon', 'Aurash', 'Avalon', 'Azzir', 'Baby Dog', 'B\'Ael', 'Ballyhoo', Bamberga', 'Banshee-44', 'Barricade', 'Baseline', 'Baxx', 'Beltrik', 'Bladedancer', 'Blight', 'Bone', 'Bracus', 'Brakion', 'Brask', 'Bray', 'Breakpoint', 'Brevin', 'Brother Vance', 'Bryl', 'Cabal', 'Caliban', 'Calus', 'Camo', 'Captain America', 'Carybdis', 'Celery', 'Celestial', 'Charlemagne', 'Chioma', 'Chronoglass', 'Cipher', 'Citan', 'Clovis', 'Coldheart', 'Colovance', 'Complex', 'Compute', 'Confused', 'Copperhead', 'Corrector', 'Cozmo-23', 'Crescent', 'Crest', 'Crota', 'Crux', 'Cryptarch', 'Dakaua', 'Darci', 'Darkblade', 'Dawnblade', 'Deathsinger', 'DeeJ', 'Defiant', 'Devastation', 'Devils', 'Devrim', 'Dictata', 'Dinklebot', 'Dogma', 'Draksis', 'Drang', 'Dredgen', 'Dreg', 'Drevis', 'Droysen', 'Dunemarchers', 'Echo', 'EDZ', 'Ego', 'Eliksni', 'Emperor', 'Emissary', 'Encore', 'Eriana-3', 'Eris Morn', 'Eternity', 'Eva Levante', 'Everis', 'Exile', 'Exo Stranger', 'Exotic', 'Fallen', 'Fatebringer', 'Feizel', 'Felwinter', 'Fenchurch', 'Finnala', 'Flashpoint', 'Foetracer', 'Foresight', 'Gatekeeper', 'Gensym', 'Ghaul', 'Ghost', 'Gilmanovich', 'Gjallarhorn', 'GodWave', 'Golden', 'Golgoroth', 'Gornuk', 'Gravekeeper', 'Grayor', 'Grenade', 'Guide', 'Gulrot', 'Halak', 'Halfdan', 'Hallowfire', 'Hammer', 'Harbinger', 'Harpy', 'Hassa', 'Haunted', 'Havoc', 'Hawkmoon', 'Hawthorne', 'Hemisphere', 'Hezen', 'Hildean', 'Hohmann', 'Holborn', 'Holliday', 'Honeycomb', 'HopeEater', 'Hunter', 'Hygiea', 'Illyn', 'Io', 'Irxis', 'Ir Yut', 'Ivonovich', 'Jacobson', 'Jagi', 'Jalaal', 'Jaren', 'Jolyon', 'Jovians', 'Judgment', 'Kadi 55-30', 'Kagathos', 'Kagoor', 'Kaharn', 'Kaliks', 'Kay', 'Keksis', 'Kells', 'Kellship', 'Khvostov', 'Kingfisher', 'Kings', 'Knight', 'Knucklehead', 'Korus', 'Kovik', 'Kraghoor', 'Kranox', 'Kressler', 'Krughor', 'Lakpha', 'Lakshmi-2', 'Lancelot', 'Lanshu', 'Legendary', 'Lincoln', 'Lissyl', 'Long Walk', 'Lokaar', 'Loken', 'Lomar', 'Lonwabo', 'Lord Saladin', 'Lord Shaxx', 'Louis', 'LV36 Captain', 'Malahayati', 'Malok', 'Malphur', 'Mamba', 'Man o\'War', 'Mara Sov', 'Maraid', 'Martyr', 'Massyrian', 'Matador 64', 'Mecher', 'Medulla', 'Mengoor', 'Merciless', 'Micha', 'MIDA', 'Milestone', 'Mindbreaker', 'Minerva', 'Minotaurs', 'Minuet', 'Mir', 'Modris', 'Moon', 'Moonrider', 'Mormu', 'M\'Orn', 'Murmur', 'Nanotech', 'Nascia', 'Nemo', 'Nessus', 'Nezarec', 'Nicha'', 'Nighthawk', 'Nightshade', 'Ning', 'Noble', 'Nolg', 'Novarro', 'Oboe', 'Offense', 'Ogre', 'Omnigul', 'Oort', 'Optimacy', 'Orbiks', 'Oracle', 'Origin', 'Oryx', 'Osiris', 'Oversoul', 'Pacific', 'Palamon', 'PallasBane', 'Parixas', 'Paskin', 'Peacekeepers', 'Peekis', 'Perseverance', 'Persuader', 'Petra', 'Philomath', 'Phoenix', 'Piccolo', 'Pinar', 'Pirsis', 'Praxic', 'Prophet', 'Prosecutor', 'Prospector', 'Protheon', 'Psion', 'Qiao', 'Qodron', 'Queenbreakers', 'Qugu', 'Quickfang', 'Quria', 'Racin', 'Radegast', 'Rafriit', 'Rahndel', 'Raiden', 'Ralph the Chicken', 'Rapture', 'Rasputin', 'Rat King', 'Red Legion', 'Redjack', 'Reefborn', 'Relentless', 'Revenge', 'Rezyl', 'Rience', 'Rift', 'Riksis', 'Riskrunner', 'Roni', 'Rose', 'SABER', 'Saint-14', 'Sardok', 'Sardon', 'Sathona', 'Savathun', 'Saviks', 'Sayeth', 'Scathelocke', 'Scavenger', 'Scorpion', 'Scout', 'Sedia', 'Segoth', 'Sekrion', 'Sepiks', 'Seven-Six-Five', 'Shadestep', 'Shadowshot', 'Shelter', 'Shieldbreaker', 'Shim', 'Shirazi', 'Shiro-4', 'Shotgun', 'Showrunner', 'Shift', 'Shuro', 'Sidearm', 'Siege Engine', 'Silent Fang', 'Silimar', 'Simiks', 'Simulator', 'Skate', 'Skolas', 'Skoriks', 'Skorri', 'Skriviks', 'Skullfort', 'Skyburners', 'Sloane', 'Sojourner', 'Solarium', 'Solkis', 'Sovereign', 'Speedpunk', 'Spindle', 'Squid', 'Starchaser', 'Starcutters', 'Stormcaller', 'Stormtrance', 'Sturm', 'Sundaresh', 'Sunshot', 'Suros', 'Sweeper Bot', 'Swiftling', 'Swordbearer', 'Sylok', 'Synthoceps', 'Ta\'Aurc', Taeko', 'Taishibethi', 'Taken', 'Tango', 'Talon', 'Taniks', 'Taox', 'Tarlowe', 'Teben', 'Techeun', 'Telesto', 'Telstar', 'Telthor', 'Tempests', 'Templar', 'Tescan', 'Tevis', 'Thalnok', 'Thaviks', 'The Speaker', 'The Traveler', 'Theosyion', 'Tho\'Ourg', 'Thrall', 'Thuria', 'Timepiece', 'Timewarp', 'Timur', 'Tinette', 'Titan', 'Token', 'Toland', 'Tover', 'Transversive', 'Trax', 'Trenn', 'Tubach', 'Tuyet', 'Uldren Sov', 'Unassailable', 'Uriel', 'Urrox', 'Urzok', 'Uzoma', 'Va\'Ase', 'Valiant', 'Valus', 'Vandal', 'Vekis', 'Veliniks', 'Velor', 'Vengeance', 'Venj', 'Verdict', 'Vestan', 'Vestian', 'Vex', 'Vigilance', 'Virixas', 'Voidwalker', 'Vorlog', 'Vosik', 'Ward', 'Warlock', 'Warmind', 'Warpriest', 'Warsat', 'Wayfarer', 'Wei Ning', 'Weksis', 'Wicked', 'Wildwood', 'Wintership', 'Wizened', 'Wolves', 'WorldRender', 'Wormfood', 'Wormwood', 'Wrecked', 'Xander 99-40', 'Xivu', 'Xol', 'Xur', 'Xyor', 'Yavek', 'Yor', 'Zahn', 'Zarin', 'Zhalo', 'Zire', 'Zydron', 'Zyre', 'Zyrok'  

hopefully those are all formatted properly. enjoy!

**Comment by megannnjay** [comment]
Remove one: 
Vestian & Vestan; Cryptarch & Crytparch; Warmind & Warminds; Techeun & Techeuns & Tescan; Bracus & Bracuses, Hildian & Hildians;

**Comment by quiscalusmajor** [comment]
those were already removed/edited except for 'Vestan', which was a term used in the Golden Age 2 grim card, and 'Tescan' is from Rezzyl Azzir: War Without End (the Tescan Valley incident). Vestan can probably be removed for pronunciation reasons, but 'tescan' and 'techeun' sound nothing alike imo.
