### ISSUE TITLE
Automate the Weekly Reset, Trials, and Xur postings in announcement channel

### ISSUE THREAD

**Issue by D0cR3d** [r-DestinyTheGame/Sweeper-Bot#169]
- [x] Xur: https://i.imgur.com/3lTOk8P.png
 - For indentation we are using :blank: emote
- [x] Trials: https://i.imgur.com/TiYfO87.png
 - Some info likely not available in the API and we can leave off / manually edit if needed.
- [x] Weekly Reset: https://i.imgur.com/tA4pMeB.png
 - Some info likely not available in the API and we can leave off / manually edit if needed.

They should be posted in the #bungie-announcements channel.

**Comment by Luminaire117** [comment]
So there's no vendor endpoint for eververse stuff

**Comment by Luminaire117** [comment]
https://github.com/r-DestinyTheGame/Sweeper-Bot/pull/170
i *think* its done, take a look
