### ISSUE TITLE
Identify LittleLight Functionality to Import

### ISSUE THREAD

**Issue by katagatame** [r-DestinyTheGame/Sweeper-Bot#2]
Please update this issue with the commands and functionality we wish to import from LittleLight.

**General Destiny Commands**
- coo
- item
- lore
- nightfall
- trials
- weekly
- xur

**Profile Related Commands**
- chars/profile
- collection
- lastpvp
- pve
- pvp
- wasted

**Destiny Text RPG Commands**
- game related commands

**General Purpose Commands**
- Google
- Reddit
- Twitter
- weather
- YouTube

**Comment by weylin** [comment]
Linking to our [LittleLight](https://github.com/weylin/CloudBot/blob/master/plugins/destiny.py) plugin and the [useage](https://gist.github.com/weylin/d0968cb5684d2deac3d116b5c9030d7f) page I started writing for posterity.

**Comment by weylin** [comment]
Some general CloudBot plugins would be nice as well, as occasionally Discord users use our IRC bridge to use the weather, or other commands.

**Comment by katagatame** [comment]
I've updated the initial issue to include weather.

What are the general CloudBot plugins we want to import specifically?

This is going to turn into a list of commands/functionality to implement.  The more specific, the better.

**Comment by danburbul** [comment]
Weekly 
Nightfall
Xur 
Trials
Lastpvp
Coo

**Comment by D0cR3d** [comment]
the weekly/nightfall/etc will be under the general !destiny command so would probably be best to just have 1 command and call from that.

**Comment by weylin** [comment]
I prefer the commands being broken out; I think nightbot handles it that way because it's a single service that's plugable with 3rd party scripts. Can be written either way really; not sure if we plan on having commands for other games.

**Comment by D0cR3d** [comment]
What about identifying the top ~5 commands and have them broken out, but still have the full !destiny <command> which is what everyone is used to. Will make it easy for people to come in and use, without learning new command format.

**Comment by weylin** [comment]
That's a very reasonable compromise. Guess it doesn't matter either way; I forgot that Discord regulars are more familiar with that than #irc crew are.

**Comment by weylin** [comment]
Other commands:

pvp
pve
wasted
lore
collection
chars/profile
item

**Comment by katagatame** [comment]
If this looks to be it, we can close this issue and roll all of the Destiny commands into #5.  If there are no other plugins, like weather, to add I will just close this issue.
