### ISSUE TITLE
Update Assignment Output

### ISSUE THREAD

**Issue by katagatame** [r-DestinyTheGame/Sweeper-Bot#22]
Update the output to be more friendly.

This applies to the following commands:
- [ ] `DestroyRole`
- [ ] `GetRole`
- [ ] `AllowRole`
- [ ] `DisallowRole`

**Comment by D0cR3d** [comment]
Remove the label "Invalid Roles are either already allowed, incorrectly typed, or not a current server role." as well as the column "Invalid Roles" if there are no invalid roles.

move the Invalid Roles label to the bottom.

**Comment by katagatame** [comment]
#35 resolves this
