### ISSUE TITLE
Update Profile Command

### ISSUE THREAD

**Issue by katagatame** [r-DestinyTheGame/Sweeper-Bot#23]
Currently just plaintext, usernames can affect Discord formatting.  Display usernames in an inline codeblock.

**Comment by JacobCallahan** [comment]
The command should look something like this (check bold text at bottom.

Command: me
Description: Profile Registration
Usage: .me ?

Argument information below...

set : Profile Registration
toggle : Toggle Main Account
flush : Flush Profile

*Running the command without an argument returns current profile information.
***Current platforms: xbl, psn**

**Comment by katagatame** [comment]
Update `.me toggle` with clearer help text.

"Please respond with the number you would like to set as active."
