### ISSUE TITLE
Test [DEV] Sweeper Bot

### ISSUE THREAD

**Issue by katagatame** [r-DestinyTheGame/Sweeper-Bot#25]
**Sweeper Bot Currently Running MASTER branch**

Please connect to [/r/DestinyTheGame-DEV](https://discord.gg/28BcgJx) Discord and test the current iteration.

Please use this [command list](https://gist.github.com/katagatame/d21ecdd1deeee3d51ca4ce7c9d716389) as a guide for testing.  Also refer to the wiki for supplemental information.

If you have any concerns, questions, or issues please comment on this issue.  We will discuss everything and make change request issues as needed.

If you do not have a PSN or XBOX account, you can just make shit up.  They just need to pass the platform username validation.

-----
**Completed Commands**

*Me*
- `.me`
- `.me set <Platform> <Handle>`
- `.me toggle`
- `.me flush`

*ListRoles*
- `.list`

*AllowRole*
- `.allow <RoleName>`
- `.allow <RoleName>, <RoleName>, ...`
- `.a <RoleName>`
- `.a <RoleName>, <RoleName>, ...`

*DisallowRole*
- `.disallow <RoleName>`
- `.disallow <RoleName>, <RoleName>, ...`
- `.d <RoleName>`
- `.d <RoleName>, <RoleName>, ...`

*GetRole*
- `.gr <RoleName>`
- `.gr <RoleName>, <RoleName>, ...`

*DestroyRole*
- `.dr <RoleName>`
- `.dr <RoleName>, <RoleName>, ...`

*SyncRoles*
- `.sync`

*HandleSearch*
- `.hs <DiscordUserName>`
- `.hs <DiscordUserMention>`

*APoD*
- `.apod`
- `.apod <r>`

*UserStats*
- `.us`

*XKCD*
- `.xkcd`
- `.xkcd <r>`
- `.xkcd <###>`

**Comment by katagatame** [comment]
I have done some preliminary testing and created the following issues:

#22 - Update Assignment Output
#23 - Update Profile Command
#24 - Update Handle Search

**Comment by katagatame** [comment]
From @JacobCallahan:

Update the help text for `.me` command to include all valid platforms.

**Comment by katagatame** [comment]
Update PC embed color to red.

**Comment by katagatame** [comment]
Update toggle with clearer help text.

"Please respond with the number you would like to set as active."

**Comment by katagatame** [comment]
`.xkcd <###>`

Add logic to let the user know if they selected an invalid comic.

**Comment by D0cR3d** [comment]
The message "You appear to have an active handle already." should re-iterate whatever platform nickname is found so the user knows what it picks up. Should also add a cancel option.

**Comment by katagatame** [comment]
This round of testing was completed.
