### ISSUE TITLE
Include valid platforms in help text for me command

### ISSUE THREAD

**Issue by JacobCallahan** [r-DestinyTheGame/Sweeper-Bot#26]
The command should look something like this (check bold text at bottom.

Command: me
Description: Profile Registration
Usage: .me <Argument>?

Argument information below...

set <Platform> <Handle> : Profile Registration
toggle                  : Toggle Main Account
flush                   : Flush Profile

*Running the command without an argument returns current profile information.
***Current platforms: xbl, psn**

**Comment by katagatame** [comment]
Closing this one, because @JacobCallahan can't follow directions. :(
