### ISSUE TITLE
Decide on Default Embed Color

### ISSUE THREAD

**Issue by katagatame** [r-DestinyTheGame/Sweeper-Bot#27]
We need to decide on the default embed color to accompany generalized embeds. (i.e. - apod, xkcd, other non-user related embeds).

Mess around with the `.color` command on DEV and choose your fave, then list it here.

Current Colors:
**PC** = 0xEF3333, PC role red from Discord
**XBL** = 0x107C10, Official Xbox green
**PSN** = 0x003791, Official PS blue

Colors that need deciding:
`.apod`
`.xkcd`
`.us`
`.allow`
`.disallow`
`.dr`
`.gr`
`.list`
`.sync`

This new color will apply to all of the colors that ARE NOT profile related, and will be used for future embeds that are also NOT profile related.

All profile related commands will be colored according to platform.

**Comment by weylin** [comment]
Any examples we can reference?

**Comment by katagatame** [comment]
I've just rolled a test command into [DEV] Sweeper Bot for everyone to test colors with.

`.color 0x206694` will output a sample embed with the specified color.  It must be in that format.

**Comment by JacobCallahan** [comment]
0x343777
#343777
rgb(52, 55, 119)
hsl(237, 39%, 34%)

**Comment by katagatame** [comment]
0x663399

**Comment by D0cR3d** [comment]
.color 0x6441a5 | twitch purple. Looks good on light and dark theme. 

https://cdn.discordapp.com/attachments/305138344021590016/306429216617005058/Screenshot_20170425-085859.png

https://cdn.discordapp.com/attachments/305138344021590016/306429217132773376/Screenshot_20170425-085830.png

**Comment by D0cR3d** [comment]
Decided, color will be `0xff8c00`
