### ISSUE TITLE
Identify GiveawayBot Functionality to Import

### ISSUE THREAD

**Issue by katagatame** [r-DestinyTheGame/Sweeper-Bot#3]
Please update this issue with the commands and functionality we wish to import from GiveawayBot.

**Comment by D0cR3d** [comment]
**Commands:**

!gstart <time> [prize] - starts a giveaway; time can be in seconds (Ex: 40 or 40s) or minutes (Ex: 3m)
!greroll [messageId] - re-rolls the specified or latest giveaway in the current channel

**Functionality:**

Upon issuing the !gstart command the bot makes a message in the same channel with info on the prize, how much time is remaining, then adds a reaction to it's own message.

Users then react with the same reaction, which enters them into the drawing. While the giveaway is active, the bot edits it's own comment once per minute until 5 minutes is remaining then once every 15 seconds.

Once the giveaway is over, the bot randomly selects someone from the reactions list, and edits its message with an @tag of the winner, and makes another message tagging the winner.

**Permissions:**

Requires either the _Manager Server_ permission or the _BotName_ permission
