### ISSUE TITLE
Test Latest Iteration, notes functionality

### ISSUE THREAD

**Issue by katagatame** [r-DestinyTheGame/Sweeper-Bot#58]
### Test Latest Iteration, notes functionality

**[r/DestinyTheGame - Dev Discord Server](https://discord.gg/28BcgJx)**
Running: **Master Branch**
Test Cycle: **24 June 17 - 26 June 17**
Available Commands: **https://gist.github.com/katagatame/d21ecdd1deeee3d51ca4ce7c9d716389**

-----
We've incorporated a couple things that we need some testing for.  Please test the bot by the following actions:

*Me Commands*
- Link your current Destiny information, platform and handle, with Sweeper Bot
- Add an alternate account
- Replace an existing account
- Toggle your main handle

*Note Commands*
- Create a new note for a user
- View a users note history
- Delete a note from a users history

*Handle Search*
This only searches for users that have previously registered with Sweeper.
- Search for user using Discord Mention
- Search for user using Discord Name, plaintext. (It also must NOT be a nickname)

*Help Commands*
- Run `.help` to see the general help command for the bot.
- Run `.help <Command Name>` to see the specific help information for that command.

**Comment by D0cR3d** [comment]
Things to adjust:

Note history should provide a max number of notes, such as the most recent 10 notes, with a '.note history all' argument to get all
Notes should require a note text and not allow an empty note
Allow adding note by userID
allow adding note by username, but without user mention (maybe confirm before adding?)

**Comment by katagatame** [comment]
*Handle Search*

**Comment by weylin** [comment]
Notes are storing but I keep losing the first word in args. Instructions unclear?

**Comment by danburbul** [comment]
Bot response when a profile is not linked should describe how to link a profile, current: 

* [1:23 PM] BOT[DEV] Sweeper Bot: No profile attributes set.

**Comment by katagatame** [comment]
Re-opening because it seems people are still finding some issues.
