### ISSUE TITLE
Update Notes Command

### ISSUE THREAD

**Issue by katagatame** [r-DestinyTheGame/Sweeper-Bot#65]
## Basic Changes
- [x] Disable ability to run command in DM
- [x] Update Notes to use the ModActions table

## Role Considerations
- [x] Restrict access to command

*Mod Assistant should have full access to the following commands: history and set. Mod Assistant should NOT have access to delete*

## Setting a Note
- [x] Update `set` to `add`
- [x] Update to allow notes to be set for plain text Discord names
- [x] Update to allow notes to be set for Discord User ID
- [x] Update to allow notes to contain Discord mentions
- [x] Update to prevent users from setting blank notes

## Display
- [x] Update display embed to use bot default embed color, specified in Constants file

## History
- [x] Update to display the most recent 5 notes
- [x] Update to allow for a full history reset
- [x] Update to show date/time of note
- [x] Add functionality to see a user's full history

## Error Messages
- [x] Update error messages to be more informative

*I intentionally set a long note to max it out, rather then tell me I was over the limit it just told me that there was an error saving the note*

**Comment by D0cR3d** [comment]
All issues resolved by PR #79
