### ISSUE TITLE
Test Latest Iteration, Role Assignment

### ISSUE THREAD

**Issue by katagatame** [r-DestinyTheGame/Sweeper-Bot#69]
**[r/DestinyTheGame - Dev Discord Server](https://discord.gg/28BcgJx)**
Running: **Master Branch**
Test Cycle: **09 July 17 - 12 July 17**
Available Commands: **https://gist.github.com/katagatame/d21ecdd1deeee3d51ca4ce7c9d716389**

-----
We've incorporated a couple things that we need some testing for.  Please test the bot by the following actions:

**Role Assignment Commands**
- Create the role reaction message in #assignment.
- Assign roles via reaction.
- Remove roles via removing your reaction.

**Profile Commands**
- Link your current Destiny information, platform and handle, with Sweeper Bot.
- Add an alternate account.
- Replace an existing account.
- Toggle your main handle.

**Handle Search Commands**
*This only searches for users that have previously registered with Sweeper.*
- Search for user, via plaintext Discord Mention.
- Search for user, via plaintext Discord Name. (nicknames will NOT work).

**User Stats Commands**
- Display your own user stats.
- Display a specific user's stats, via Discord mention.
- Display a specific user's stats, via plaintext Discord Name. (nicknames will work).

**Help Commands**
- Run `.help` to see the general help command for the bot.
- Run `.help <Command Name>` to see the specific help information for that command.

**Notes Commands**
These commands have not been updated since the last round of testing.

**Comment by katagatame** [comment]
**Handle Search Commands**
- Update display to wrap handles in inline codeblocks, this will accommodate any characters that Discord reads as formatting.

**Comment by TheRealBGoat** [comment]
Couple of issues to be addressed:

- After setting my platform following a flush, SweeperBot's "typing" status was stuck on
- In the toggle embed, the 1, 2 and 3 icons all smush together and would like nicer if there was a bit of whitespace between them

Will add more if I see it.
