### ISSUE TITLE
Auto Voice Channel Creation

### ISSUE THREAD

**Issue by katagatame** [r-DestinyTheGame/Sweeper-Bot#8]
Have a bank of channels that create/delete themselves based on current usage.

**Comment by D0cR3d** [comment]
Voice channel creation logic:

Channel Format:
---------------
Title: 📢 Fireteam <Char Name>
Users: Default 6 unless specified in adv settings
Permissions:
- The Vanguard: Set as neutral (nothing enabled/disabled)
- Discord Chat Mods: Set as neutral (nothing enabled/disabled)
- Mod Assistant: Set as neutral (nothing enabled/disabled)
- Everyone: Connect, Speak, Push To Talk

<Char Name> is a random name not already used from characters in game such as Cayde-6, Zavala, Ikora Rey, Taniks, etc

So it'd be '📢 Fireteam Toland'


Timing logic:

- Minimum of 2 _OPEN_ channels at all times.

- 1. When it sees that someone has entered an existing of the _2_ open channels, it starts a 2 minute countdown. If someone is still in that channel after 2 minutes, another channel is created.

- 1A. If the channel is emptied during that 2 minute countdown, the countdown to _create_ another channel is cancelled and no new channels are made. A new countdown is created per 1C.

- 1B. If someone enters the last remaining open channel while a countdown is going on then 1 channel is immediatly created.
    - Ex: Channel W and X exist. Someone enters Channel W so a 2 minute countdown starts (to create another). At 1 minute someone enters channel X so channel Y is immediatly created with a 2 minute countdown on channel X and 1 minute remaining on Channel W leaving 1 open channel and 2 in use.

- 1C. If someone exists a channel a 2 minute countdown is started. If no one re-enters that channel during those 2 minutes the channel is then destroyed. If someone does enter during those 2 minutes grace period the timer is cancelled.

**Comment by katagatame** [comment]
#114 #115 #116 #117 #118 resolved this.
