### ISSUE TITLE
Allow IRC role to be self-assigned

### ISSUE THREAD

**Issue by D0cR3d** [r-DestinyTheGame/Sweeper-Bot#89]
Building off the `!create spoiler/faction/platform` command to add a `!create ircRole` command so that someone can self-assign access to #irc-bridge channel.

- [ ] Validate IRC role has correct permissions (currently used by the IRC bot)
- [ ] Create and upload emoji to the DEV server
- [ ] Upon clicking the emoji the bot DMs the user sending them the rules of the IRC channel, type of content that they would see there (Adult conversations that could get heated such as politics, sports, mildly NSFW material (minus porn/gore), the slightly adjusted ruleset, etc). Asks them to confirm they are ok with that and then assigns them the role.

This is a fairly simple task due to much of the work being done already in the !create command itself so should be a great task for anyone to jump on.

**Comment by katagatame** [comment]
This is no longer needed as the IRC bridge is no longer connected to Discord.
